### ISSUE TITLE
Never entering inside of before-existing-directory

### ISSUE THREAD

**Issue by daruj** [shaketbaby/directory-named-webpack-plugin#12]
I tried to use this plugin with webpack v:"2.2.1" and it did not work. So I've went deep into the code and I found out it never enters inside of `resolver.plugin('before-existing-directory', function (request, callback) { ... });`

**Comment by daruj** [comment]
It seems that plugin was removed from https://github.com/webpack/enhanced-resolve/blob/7df23d64da27cd76b09046f9b9ffd61480c0ddca/test/plugins.js

**Comment by shaketbaby** [comment]
Thanks for reporting, I'll have a look.

**Comment by shaketbaby** [comment]
Just did some tests with the latest Webpack v2.3.2 and v2.2.1, they both built the bundle successfully. Does it still not work for you? Are you able to provide some more info? Maybe some example codes and webpack config that don't work?

**Comment by shaketbaby** [comment]
Closing this as it seems to working fine with my own testing.

**Comment by gserrg** [comment]
This happens when the plugin is mistakenly added not to resolve, but to common plugins.
