### ISSUE TITLE
include and exclude

### ISSUE THREAD

**Issue by mkg0** [shaketbaby/directory-named-webpack-plugin#14]
i think this plugin needs include and exclude properties to options. what do you think?

**Comment by shaketbaby** [comment]
Maybe, but those can be achieved by specifying a `ignoreFn`, which provides the ultimate flexibility in my opinion.

**Comment by mkg0** [comment]
You are right, it provides this requirement(also i used it like this) but most use cases need it only "include" and "exclude" approach just like loaders. I think it is more readable and _webpack way_.

**Comment by shaketbaby** [comment]
Sure, would you be able to create a PR for this? :)

**Comment by mkg0** [comment]
yes, you can assign me :)
