### ISSUE TITLE
Have you gotten this working with flow? 

### ISSUE THREAD

**Issue by bachstatter** [shaketbaby/directory-named-webpack-plugin#16]

**Comment by shaketbaby** [comment]
I've never used flow, what's the issue?

**Comment by shaketbaby** [comment]
Closing as can't do much without further info.

**Comment by Rodeoclash** [comment]
The issue here with flow is it doesn't use the same resolvers as webpack / this library. It might be possible with use of flows name mapper config to produce some regex that would achieve the same effect in resolving files.

**Comment by todesstoss** [comment]
same here, 
can't use flow with this import: 

`[flow] ./components/Component (Required module not found)
`
while my file is in  ./components/Component/Component.js

**Comment by todesstoss** [comment]
I hope it will help someone:

you can add this to your `.flowconfig`

```
[options]
module.name_mapper='\(/[a-zA-Z]+$\)' -> '\1\1'
```
I'm, also using aliases for my src directory, and I can't understand how to pipe few regexp to one import string. The config above works well for relative imports, without aliases.
