### ISSUE TITLE
Webpack 3 can't resolve 'fs' and 'net'

### ISSUE THREAD

**Issue by zorahrel** [shaketbaby/directory-named-webpack-plugin#17]
I updated to Webpack 3, if I add the plugin in resolve's plugins list I have this error in console.

```ERROR in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'fs' in '/MY-PROJ-DIR/node_modules/debug/src'
 @ ./node_modules/debug/src/node.js 184:15-28
 @ ./node_modules/debug/src/index.js
 @ ./node_modules/sockjs-client/lib/main.js
 @ ./node_modules/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/index.js

ERROR in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'net' in '/MY-PROJ-DIR/node_modules/debug/src'
 @ ./node_modules/debug/src/node.js 191:16-30
 @ ./node_modules/debug/src/index.js
 @ ./node_modules/sockjs-client/lib/main.js
 @ ./node_modules/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/index.js```

**Comment by shaketbaby** [comment]
I haven't tested with Webpack 3 yet, will look into it. `fs` and `net` look like Node.js built in modules, are you importing them in your client codes? Are you able to provide some more info? Project structure, webpack config file, etc if possible. Thanks!

**Comment by shaketbaby** [comment]
Looks like `sockjs-client` will `require` module `debug` if it not PROD env which tries to detect and ends up importing the file for `Node.js` instead of browser. Can you try to specify `honorPackage` option to look for browser first? 
```javascript
new DirectoryNamedWebpackPlugin({
  honorPackage: ["browser", "main"],
  // any other options needed
})
```
Please let me know if this works.

**Comment by shaketbaby** [comment]
Can you please let me know if this plugin works for you now? Thanks!

**Comment by shaketbaby** [comment]
I am closing this now as I have upgraded WP to version 3 for our project and the plugin works fine. Can't do much without further info.

**Comment by tomasfrancisco** [comment]
Hi @shaketbaby, I was having the same problem here.
The 'honorPackage' has resolved the issue.
