### ISSUE TITLE
Update peerDependencies for webpack 3

### ISSUE THREAD

**Issue by lipolyakov** [shaketbaby/directory-named-webpack-plugin#20]
I have tried you plugin with webpack 3, it work nicely! But I see next warning while install:

> warning "directory-named-webpack-plugin@2.2.2" has incorrect peer dependency "webpack@^2.2.0".

**Comment by shaketbaby** [comment]
Yeah, it's because the major version of Webpack, I'll fix it.

**Comment by lipolyakov** [comment]
👍

**Comment by shaketbaby** [comment]
v2.2.3 released, should be okay now.
