### ISSUE TITLE
is possible to resolve with respecting name of entry?

### ISSUE THREAD

**Issue by plandem** [shaketbaby/directory-named-webpack-plugin#21]
Hello! Is possible to resolve with respecting name of entry?

E.g., in my case I have

alias:
app -> /web/...
app -> /desktop/...

I have to run twice for each type of entry, because I can't resolve alias correctly. Is it possible to use your login and add logic for entry name?

**Comment by shaketbaby** [comment]
I think so, can provide a `transformFn` for resolving with any logic required.

**Comment by shaketbaby** [comment]
How did it go? Did `transformFn` work for you?

**Comment by plandem** [comment]
I went by other way (own plugin), but finally drop idea to have same alias for differ app(because I also need a different target) at the same config.

**Comment by shaketbaby** [comment]
cool
