### ISSUE TITLE
Extend transformFn

### ISSUE THREAD

**Issue by talkshowhost** [shaketbaby/directory-named-webpack-plugin#23]
Is it possible to expand the transformFn with further customization?

For example, I would like to return every file that ends in **.module.js**. 

This way I can have a module under **users** in a folder called **form** whereas the module filename would be _users.form.module.js_. This way I could include in _users.module.js_ something like this

`import usersFormModule from './form';`

The way it is now, I can only do it with **index** file or pointing exactly to the filename. Having the name of the module being _form.module.js_ would defeat the purpose if I have a form on another folder and the filename would have to be the same.

**Comment by shaketbaby** [comment]
Yes, will need to know the full path to do what you described, think I can pass the full path and the original resolving request to `transformFn` in addition to just `basename` as it is now.

**Comment by shaketbaby** [comment]
I've created a PR #24 , would you please be able to confirm that it meets your requirement?

**Comment by shaketbaby** [comment]
Cool, I have released a new version 2.3.0.
