### ISSUE TITLE
Hook "before-existing-directory" does not working

### ISSUE THREAD

**Issue by dmitrygorbenko** [shaketbaby/directory-named-webpack-plugin#25]
Hi,
The plugin is not working for me. Webpack version is 3.10.0
Afaik, there is no such hook anymore:
https://webpack.js.org/api/compiler/#event-hooks

Can you take a look ?

Thanks,
Dima

**Comment by shaketbaby** [comment]
Thanks for reporting, but this plugin is a resolver plugin. I'll have a look

**Comment by shaketbaby** [comment]
I have just upgraded Webpack to 3.10.0 and all tests are still passing. Are you able to provide some more info about the error? And your Webpack configuration if that's okay.

**Comment by shaketbaby** [comment]
Are you still having the issue? Can't do much without more info as things are working fine for me.

**Comment by BTMPL** [comment]
This issue now exist in Webpack 4 where the plugin system was rewoerked, and there's no "before-existing-directory", there's "existingDirectory" hook now, but it looks like it's not compatible.

**Comment by shaketbaby** [comment]
Thanks, I'll release a new version that works will Webpack 4 ASAP.

**Comment by shaketbaby** [comment]
I have upgrade enhanced-resolve to v4 and all the tests are still passing, which should be the case as Resolver in Webpack v4 is backward compatible per the migration guide https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

As suggested in the guide, have updated codes to use new plugin system. Tests are passing, will release soon after some more testing.

**Comment by shaketbaby** [comment]
Have released v4.0.0 to go with Webpack 4, closing this now.
