### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by CloudPower97** [shaketbaby/directory-named-webpack-plugin#33]
Hello,
I'm trying to figure out what I'm doing wrong, because it doesn't seems to work at all for me.
Let me start by saying that I'm using [craco](https://github.com/sharegate/craco), so this might be the problem (I don't think so, haven't had problem with other plugin until now).

Here is how i configured it: 
```javascript
    webpack: {
      resolve: {
        plugins: [new DirectoryNamedWebpackPlugin()],
      },
      alias: {
        components: path.join(paths.appSrc, 'components'),
        containers: path.join(paths.appSrc, 'containers'),
        hoc: path.join(paths.appSrc, 'hoc'),
        style: path.join(paths.appSrc, 'style'),
        libs: path.join(paths.appSrc, 'libs'),
        assets: path.join(paths.appSrc, 'assets'),
      },
    },
```

That's the error I have 

```
Failed to compile.

./src/containers/Azienda/Azienda.js
Module not found: Can't resolve 'components/Parallax' in '/home/claudio/Documents/Educabile/educabile-web/src/containers/Azienda'
```

Of course there is a file named `Parallax.js` in `components/Parallax`.

Please, can you take a look at it whenever you can?
Thanks in advance and keep up the good work!

**Comment by shaketbaby** [comment]
What version of Webpack are you using? Did you have it working before but not anymore?
Looking at the error, looks like it can resolve `containers/Azienda` but not `components/Parallax`, is this correct? Also, can it resolve other `components`?

**Comment by shaketbaby** [comment]
Sorry, didn't get time to look into this.  I was wondering if it is to do with `alias`, but looks like it's not. Also I don't understand how it can resolve `containers/Azienda` but not `components/Parallax`. What's the difference between `containers` and `components`? 

Also, what is your `resolve.modules` looks like?

**Comment by CloudPower97** [comment]
Don't worry, it's ok :smile: 
Just to recap:
```javascript
import React from 'react'
import Caption from 'components/Capiton/Caption'
...
```

Does work, while
```javascript
import React from 'react'
import Caption from 'components/Capiton'
...
```

doesn't.

Also tried without _webpack_ `alias`, hence

```javascript
import React from 'react'
import Caption from '../components/Capiton'
....
```

and it still doesn't work.

Another thing I tried is the include options:

```javascript
    webpack: {
      resolve: {
        plugins: [
          new DirectoryNamedWebpackPlugin({
            include: [
              path.resolve(path.join(paths.appSrc, 'components')),
              path.resolve(path.join(paths.appSrc, 'containers')),
            ],
          }),
        ],
      },
      alias: {
        components: path.join(paths.appSrc, 'components'),
        containers: path.join(paths.appSrc, 'containers'),
      },
    },
```

with no luck as well.

So it seems that the problem is indeed with `directory-named-webpack-plugin`.

Just do not know why.

It simply always says
`Module not found: Can't resolve 'components/Capiton'`

**Comment by CloudPower97** [comment]
Hey, @shaketbaby , sorry to ask, do you have any updates on this issue? :grin:

**Comment by derozn** [comment]
@CloudPower97 Just looking at your recap comment and noticed you are importing from
```js
import Caption from '../components/Capiton'
```
Since the directory is named `Capiton` and the file you're wanting to import is `Caption` it won't resolve correctly as they both have different names.

Correct me if I'm wrong, but if you was to have a file called `Capiton` instead of `Caption` then it would resolve.

**Comment by shaketbaby** [comment]
Thanks @derozn , you might be correct. The file name needs to be same as directory name.
