### ISSUE TITLE
TypeError: resolver.ensureHook is not a function

### ISSUE THREAD

**Issue by elijah-penney** [shaketbaby/directory-named-webpack-plugin#37]
**Test Repo:** (replication commands in the repo)
https://github.com/elijah-penney/self-built-react

**Description:**
Upon adding `new DirectoryNamedWebpackPlugin()` to my webpack.common.js, the error immediately appears on any build that utilizes that config. Adding a config object or `true` does not change the results of the bug.

**Full Error:**
```javascript
TypeError: resolver.ensureHook is not a function
    at module.exports.doApply (C:\Users\Tandry\Documents\development\self-built-react\node_modules\directory-named-webpack-plugin\index.js:28:25)
    at webpack (C:\Users\Tandry\Documents\development\self-built-react\node_modules\webpack\lib\webpack.js:51:13)
    at startDevServer (C:\Users\Tandry\Documents\development\self-built-react\node_modules\webpack-dev-server\bin\webpack-dev-server.js:94:16)
    at C:\Users\Tandry\Documents\development\self-built-react\node_modules\webpack-dev-server\bin\webpack-dev-server.js:166:3
    at C:\Users\Tandry\Documents\development\self-built-react\node_modules\webpack-dev-server\lib\utils\processOptions.js:33:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Versions:**
- directory-named-webpack-plugin: ^4.0.1
- webpack: ^4.41.5
- webpack-cli": ^3.3.10
- webpack-dev-server": ^3.10.2
- webpack-merge": ^4.2.2
- enhanced-resolve: 4.1.1

I reviewed #28 which appears to have the same error but pertaining to using an older version of Webpack with Storybook. Since I'm not using Storybook, nor an older version of Webpack, the solutions in that ticket didn't resolve my issue.

Any ideas?

**Comment by elijah-penney** [comment]
Looks like I was just missing an object layer. I had:

```
plugins: [
    new DirectoryNamedWebpackPlugin()
]
```
instead of:

```
resolve: {
    plugins: [
      new DirectoryNamedWebpackPlugin()
    ]
  }
```

**Comment by shaketbaby** [comment]
That was my suspicion and was going to ask but I was distracted and forgot. Sorry about that and glad you worked it out.
