### ISSUE TITLE
directory-named-webpack-plugin doesn't work with typescript 

### ISSUE THREAD

**Issue by g8up** [shaketbaby/directory-named-webpack-plugin#38]
refer to https://webpack.js.org/configuration/configuration-languages/#typescript ， I change my `webpack.conf.js` to typescript `webpack.conf.ts`.

An error come from tslint: 
>  Only a void function can be called with the 'new' keyword.ts(2350)

as I config like below:
```js
  var DirectoryNamedWebpackPlugin = require("directory-named-webpack-plugin");

  resolve: {
    plugins: [
      new DirectoryNamedWebpackPlugin()
    ]
  }
```

**Comment by shaketbaby** [comment]
Looks like tslint checks if the constructor returns a value and disallow that. You don't have to use `new`, it's not necessary. You can just do
```ts
  var directoryNamedWebpackPlugin = require("directory-named-webpack-plugin");

  resolve: {
    plugins: [
      directoryNamedWebpackPlugin()
    ]
  }
```
